version: "3.3"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "0.0.0.0:1935:1935"
      - "0.0.0.0:8080:8080"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls
    restart: unless-stopped

  auth:
    build: ./auth
    ports:
      - "0.0.0.0:8000:8000"
    container_name: auth_server
    restart: unless-stopped